version: "3.8"

services:
  frontend:
    cpus: 0.1

    image: ngocphuc24/uek223frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - 8014:3000
    env_file:
      - .env

  backend:
    mem_limit: 512M
    cpus: 0.2

    image: ngocphuc24/uek223backend
    container_name: backend
    ports:
      - 8099:8099
    env_file:
      - .env
    depends_on:
      - db
  db:
    mem_limit: 128m
    cpus: 0.05

    image: "postgres:10-alpine"
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
