version: '3.8'

services:
  frontend:
    cpus: 0.1

    image: kunfi/frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - 8001:3000
    env_file: 
      - .env
  backend:
    mem_limit: 512M
    cpus: 0.2

    image: kunfi/backend
    container_name: backend
    depends_on:
      - db
    ports:
      - 8086:8086
    env_file: 
      - .env

  db:
    mem_limit: 128m
    cpus: 0.05

    image: 'postgres:10-alpine'
    container_name: db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgres'
